coverage:
  status:
    project:
      fileencryption:
        target: 80%
        threshold: 5%
        flags:
          - fileencryption
      passwordmanager:
        target: 80%
        threshold: 5%
        flags:
          - passwordmanager

flags:
  fileencryption:
    paths:
      - Projects/FileEncryption/src/
    carryforward: true
  passwordmanager:
    paths:
      - Projects/PasswordManager/src/
    carryforward: true

ignore:
  - "Projects/FileEncryption/src/benchmark/benchmark.cpp"
  - "Projects/FileEncryption/src/common/main.cpp"
  - "Projects/FileEncryption/src/gui/"
  - "Projects/FileEncryption/src/tests/"
  - "Projects/PasswordManager/src/common/main.cpp"
  - "Projects/PasswordManager/src/gui/"
  - "Projects/PasswordManager/src/tests/"
